default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-ast
    - id: check-case-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-executables-have-shebangs
    - id: mixed-line-ending
      args: ['--fix=lf']
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort
        args:
          - --profile=black
          - --filter-files
  - repo: https://github.com/ambv/black
    rev: 21.5b2
    hooks:
    - id: black
      language_version: python3.8
  - repo: https://github.com/0xdade/pipfile-sort
    rev: a5eb0727d443d11224a0d21d57d0f0e43e36f19c
    hooks:
      - id: pipfile-sort
